<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        // Удаляем старые записи (без TRUNCATE, чтобы избежать конфликта внешних ключей)
        DB::table('users')->delete();

        $users = [
            // Администратор
            [
                'login' => 'admin@ugrasu.ru',
                'full_name' => 'Администратор Системы',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'school_code' => null,
                'active' => 1,
                'school' => 'Администрация',
                'school_short' => 'АДМ',
                'avatar' => null,
            ],
            // Директора
            [
                'login' => 'o_samarina@ugrasu.ru',
                'full_name' => 'Самарина Ольга Владимировна',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 1,
                'active' => 1,
                'school' => 'Инженерная школа цифровых технологий',
                'school_short' => 'ИШЦТ',
                'avatar' => null,
            ],
            [
                'login' => 'm_korolev@ugrasu.ru',
                'full_name' => 'Королев Максим Игоревич',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 7,
                'active' => 1,
                'school' => 'Высшая нефтяная школа',
                'school_short' => 'ВНШ',
                'avatar' => null,
            ],
            [
                'login' => 'd_osipov@ugrasu.ru',
                'full_name' => 'Осипов Дмитрий Сергеевич',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 9,
                'active' => 1,
                'school' => 'Политехническая школа',
                'school_short' => 'ПТШ',
                'avatar' => null,
            ],
            [
                'login' => 'n_filimonova@ugrasu.ru',
                'full_name' => 'Филимонова Наталья Владимировна',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 2,
                'active' => 1,
                'school' => 'Высшая школа гуманитарных наук',
                'school_short' => 'ВШГН',
                'avatar' => null,
            ],
            [
                'login' => 's_senichenko@ugrasu.ru',
                'full_name' => 'Сениченко Сергей Андреевич',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 4,
                'active' => 1,
                'school' => 'Высшая школа физической культуры и спорта',
                'school_short' => 'ВШФКС',
                'avatar' => null,
            ],
            [
                'login' => 't_antofeeva@ugrasu.ru',
                'full_name' => 'Антофеева Татьяна Владимировна',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 5,
                'active' => 1,
                'school' => 'Высшая экологическая школа',
                'school_short' => 'ВЭШ',
                'avatar' => null,
            ],
            [
                'login' => 'e_kotsyurko@ugrasu.ru',
                'full_name' => 'Коцюрко Елена Петровна',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 8,
                'active' => 1,
                'school' => 'Высшая школа права',
                'school_short' => 'ВШП',
                'avatar' => null,
            ],
            [
                'login' => 'a_skurikhin@ugrasu.ru',
                'full_name' => 'Скурихин Александр Александрович',
                'password' => Hash::make('1234'),
                'role' => 'director',
                'school_code' => 6,
                'active' => 1,
                'school' => 'Высшая школа цифровой экономики',
                'school_short' => 'ВШЦЭ',
                'avatar' => null,
            ],
            // Члены комиссии (member)
            [
                'login' => 'a_shevchenko@ugrasu.ru',
                'full_name' => 'Шевченко Алеся Сергеевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 1,
                'active' => 1,
                'school' => 'Инженерная школа цифровых технологий',
                'school_short' => 'ИШЦТ',
                'avatar' => 'uploads/avatars/avatar_19_1773983830.JPG',
            ],
            [
                'login' => 'i_ananina@ugrasu.ru',
                'full_name' => 'Ананьина Ирина Викторовна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 7,
                'active' => 1,
                'school' => 'Высшая нефтяная школа',
                'school_short' => 'ВНШ',
                'avatar' => null,
            ],
            [
                'login' => 't_romanova@ugrasu.ru',
                'full_name' => 'Романова Татьяна Ивановна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 7,
                'active' => 1,
                'school' => 'Высшая нефтяная школа',
                'school_short' => 'ВНШ',
                'avatar' => null,
            ],
            [
                'login' => 'y_kozlova@ugrasu.ru',
                'full_name' => 'Козлова Юлия Сергеевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 9,
                'active' => 1,
                'school' => 'Политехническая школа',
                'school_short' => 'ПТШ',
                'avatar' => null,
            ],
            [
                'login' => 'i_kuznecova@ugrasu.ru',
                'full_name' => 'Кузнецова Ирина Николаевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 9,
                'active' => 1,
                'school' => 'Политехническая школа',
                'school_short' => 'ПТШ',
                'avatar' => null,
            ],
            [
                'login' => 'a_lyutarevich@ugrasu.ru',
                'full_name' => 'Лютаревич Александр Геннадьевич',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 9,
                'active' => 1,
                'school' => 'Политехническая школа',
                'school_short' => 'ПТШ',
                'avatar' => null,
            ],
            [
                'login' => 'm_slobodyan@ugrasu.ru',
                'full_name' => 'Слободян Малика Лутаевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 6,
                'active' => 1,
                'school' => 'Высшая школа цифровой экономики',
                'school_short' => 'ВШЦЭ',
                'avatar' => null,
            ],
            [
                'login' => 't_ladyzhenskaya@ugrasu.ru',
                'full_name' => 'Ладыженская Татьяна Петровна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 6,
                'active' => 1,
                'school' => 'Высшая школа цифровой экономики',
                'school_short' => 'ВШЦЭ',
                'avatar' => null,
            ],
            [
                'login' => 'e_razdrokov@ugrasu.ru',
                'full_name' => 'Раздроков Евгений Николаевич',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 6,
                'active' => 1,
                'school' => 'Высшая школа цифровой экономики',
                'school_short' => 'ВШЦЭ',
                'avatar' => null,
            ],
            [
                'login' => 'v_samarin@ugrasu.ru',
                'full_name' => 'Самарин Валерий Анатольевич',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 1,
                'active' => 1,
                'school' => 'Инженерная школа цифровых технологий',
                'school_short' => 'ИШЦТ',
                'avatar' => null,
            ],
            [
                'login' => 'n_ivanova@ugrasu.ru',
                'full_name' => 'Иванова Наталья Дмитриевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 1,
                'active' => 1,
                'school' => 'Инженерная школа цифровых технологий',
                'school_short' => 'ИШЦТ',
                'avatar' => null,
            ],
            [
                'login' => 'e_chelack@ugrasu.ru',
                'full_name' => 'Челак Елена Анатольевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 2,
                'active' => 1,
                'school' => 'Высшая школа гуманитарных наук',
                'school_short' => 'ВШГН',
                'avatar' => null,
            ],
            [
                'login' => 'a_mironov@ugrasu.ru',
                'full_name' => 'Миронов Андрей Валерьевич',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 2,
                'active' => 1,
                'school' => 'Высшая школа гуманитарных наук',
                'school_short' => 'ВШГН',
                'avatar' => null,
            ],
            [
                'login' => 'k_russu@ugrasu.ru',
                'full_name' => 'Руссу Ксения Ринатовна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 2,
                'active' => 1,
                'school' => 'Высшая школа гуманитарных наук',
                'school_short' => 'ВШГН',
                'avatar' => null,
            ],
            [
                'login' => 'n_nenenko@ugrasu.ru',
                'full_name' => 'Нененко Наталья Дмитриевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 4,
                'active' => 1,
                'school' => 'Высшая школа физической культуры и спорта',
                'school_short' => 'ВШФКС',
                'avatar' => null,
            ],
            [
                'login' => 'e_gorbunova@ugrasu.ru',
                'full_name' => 'Горбунова Елена Николаевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 8,
                'active' => 1,
                'school' => 'Высшая школа права',
                'school_short' => 'ВШП',
                'avatar' => null,
            ],
            [
                'login' => 's_hohrin@ugrasu.ru',
                'full_name' => 'Хохрин Сергей Александрович',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 8,
                'active' => 1,
                'school' => 'Высшая школа права',
                'school_short' => 'ВШП',
                'avatar' => null,
            ],
            [
                'login' => 'a_kisluhina@ugrasu.ru',
                'full_name' => 'Кислухина Анастасия Алексеевна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 8,
                'active' => 1,
                'school' => 'Высшая школа права',
                'school_short' => 'ВШП',
                'avatar' => null,
            ],
            [
                'login' => 's_esipova@ugrasu.ru',
                'full_name' => 'Есипова Светлана Александровна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 5,
                'active' => 1,
                'school' => 'Высшая экологическая школа',
                'school_short' => 'ВЭШ',
                'avatar' => null,
            ],
            [
                'login' => 'a_zaikin@ugrasu.ru',
                'full_name' => 'Заикин Александр Васильевич',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 5,
                'active' => 1,
                'school' => 'Высшая экологическая школа',
                'school_short' => 'ВЭШ',
                'avatar' => null,
            ],
            [
                'login' => 'a_niyazova@ugrasu.ru',
                'full_name' => 'Ниязова Анастасия Викторовна',
                'password' => Hash::make('1234'),
                'role' => 'member',
                'school_code' => 5,
                'active' => 1,
                'school' => 'Высшая экологическая школа',
                'school_short' => 'ВЭШ',
                'avatar' => null,
            ],
        ];

         DB::table('users')->insert($users);
    }
}